# For layers this is proposed, but this did not work. Cpython files were not in the correct place, need to deepdive

FROM public.ecr.aws/lambda/python:3.12

RUN pip install --upgrade pip \
    && pip install pyarrow -t /opt/python

CMD [ "bash" ]
